# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
# Unable to inspect table 'Achievement'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Company'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Direction'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Education'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Employer'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Events'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Faculty'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Group_'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'List_of_Achievementsreferences'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Profile'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Project'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Project_list'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Specialization'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Student'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Vacancy'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'Work'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'auth_group'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'auth_group_permissions'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'auth_permission'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'auth_user'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'auth_user_groups'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'auth_user_user_permissions'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'django_admin_log'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'django_content_type'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'django_migrations'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'django_session'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
# Unable to inspect table 'main_task'
# The error was: <lambda>() missing 1 required positional argument: 'collation'
