# Generated by Django 3.0 on 2021-05-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210519_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'managed': False},
        ),
    ]
