# Generated by Django 3.0 on 2021-06-02 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_note'),
        ('mainapp', '0003_auto_20210519_1210'),
    ]

    operations = [
    ]
