# Generated by Django 3.0 on 2021-06-07 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_merge_20210603_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
